# --------------------------------------------------
# Site settings

title: dbt Events
description: Meet dbt creators and members of the community in person! Here’s where we’ll be speaking, hosting, or attending. Have an event you’d like to share?
owner: http://github.com/fishtown-analytics
repo: https://github.com/fishtown-analytics/dbt-community-events
robots: true

nav_links:
  home: https://www.getdbt.com
  signup: https://cloud.getdbt.com/signup

# --------------------------------------------------
# Site imagery

favicon: /favicon.ico
avatar: /ui/img/graph/avatar.png
poster: /ui/img/graph/poster.png

# --------------------------------------------------
# Build settings

includes_dir: _config/_includes
layouts_dir: _config/_layouts

sass:
  style: compressed
  sass_dir: ui/_sass

collections:
  content:
    output: true
    permalink: /:path/

defaults:
-
  scope:
    path: ""
    type: "content"
  values:
    layout: "page"
